### ISSUE TITLE
Use select field for HTTP status

### ISSUE THREAD

**Issue by mbrodala** [froemken/url_redirect#1]
It should be doable to provide a `select` field for the HTTP status field.

Using `ReflectionClass::getConstants()` it should be easy to get all constants from `HttpUtility`, filter them by the ones starting with `HTTP_STATUS_` and put them as options into the select field.

**Comment by froemken** [comment]
Damn, you're fast ;-) I havn't made that extension public on Twitter nor on Facebook.
Ticket: accepted

**Comment by mbrodala** [comment]
I've subscribed to the TER feed. ;-)

**Comment by froemken** [comment]
Hi @mbrodala 

I have just uploaded a new version to TER as you may have seen allready :-)
Thank you for that hint.

Stefan

**Comment by mbrodala** [comment]
Thanks for the quick update. :-)
