### ISSUE TITLE
Redirect not working with trailing slash

### ISSUE THREAD

**Issue by h3nn3s** [froemken/url_redirect#2]
Currently URLs with a trailing slash are not working.

StefanFroemken\UrlRedirect\Hooks\PreProcess::redirect() is trimming Slashes at the beginning and the end of the Request_Uri

**Comment by froemken** [comment]
Hello @h3nn3s 

in current master I have removed all trimming. For now it's up to the user to prepend or append the slashes. Would be more like .htaccess. I have added some hints in hope that our users will not forget to prepend the slash anymore.

Stefan

**Comment by h3nn3s** [comment]
I am fine with this solution, the same was with Realurl v1 - thanks.
