### ISSUE TITLE
Import redirects from CSV

### ISSUE THREAD

**Issue by mbrodala** [froemken/url_redirect#4]
It would be useful if one could to a mass-import of redirects from a CSV file.

The format would be obvious:

```
request_uri,target_uri
```

**Comment by froemken** [comment]
Accepted. Do you have a list of all allowed CSV Mimetypes? I think there are 6 or 8 valid mimetypes which I have to check. I think I would add some CSV configuration in ExtensionManager to configure seperator, escaping chars. Would that be OK for you?

**Comment by mbrodala** [comment]
I am not aware of multiple mimetypes but having some configuration in the EM would be useful indeed. But if this is added e.g. as command these options should be configurable there, e.g.:

    redirects:importcsv --separator ";" path/to/redirects.csv

**Comment by froemken** [comment]
I have just uploaded a new version with an importer in BE module. There you can also set separator, quote char and escape char. Currently only request URI, target URI and http status will be imported. Version 1.2.0 will be available on TER within next 15 minutes.

**Comment by mbrodala** [comment]
Thanks. :-) As usual I'd prefer a CLI command (no timeout, etc.) but this will be useful in any case.
