### ISSUE TITLE
Uncaught TYPO3 Exception, Call to a member function getDocHeaderComponent() on null 

### ISSUE THREAD

**Issue by wowaTYPO3** [froemken/url_redirect#8]
After trying to create a redirect manually, I get an uncaught exception in the backend module.

![2017-09-21_09-00-29](https://user-images.githubusercontent.com/343511/30682838-64ed35ea-9eab-11e7-9cdf-8d50a5fa76da.jpg)

![2017-09-21_08-56-58](https://user-images.githubusercontent.com/343511/30682790-2e4b0f80-9eab-11e7-807a-0adef8a2104a.jpg)

**Comment by froemken** [comment]
Hello Wolfgang,

thank you for this report. I have just uploaded a new version 1.2.1 to GitHub and TER.
Have fun.

Stefan
